### ISSUE TITLE
Steuerung über die Datenpunkte nicht mehr möglich.

### ISSUE THREAD

**Issue by Menne01** [instalator/iobroker.kodi#1]
Hallo,
seit dem letzten upgrade zur Version 2.0.8 funktionieren Play, Pause und Stop über die Datenpunkte nicht mehr.
Auch der Status bleibt auf Stop. Es kommt einen vor, als wäre alles eingefroren.
Über die Weboberfläche funktioniert die Steuerung...

...ich bin zur vorigen Version zurück, musste aber feststellen das es trotzdem nicht mehr funktionierte.
Es blieb mir nichts anderes übrig und musste ein Full-Backup einzuspielen.

**Comment by instalator** [comment]
Я не поддерживаю основную ветку

**Comment by Menne01** [comment]
!?
...in German or English, Please.
