### ISSUE TITLE
Multi User (Profiles)

### ISSUE THREAD

**Issue by mikiline** [instalator/ioBroker.kodi#18]
@instalator 

Hi,

Adapter läuft super mit dem 1. User den ich erstellt habe.
Logge ich mich allerdings mit einem anderen Profil ein, geht es nicht mehr.
Es scheint als werden andere Profile irgendwie anders behandelt. 

Weiss jemand wieso das so ist? oder was ich tun kann um das Problem zu beheben?

Die Profile werden benötigt, da ich meine FSK12 Filme frei habe und die FSK18 sind gesperrt (der Adapter funktioniert für die FSK18 Filme, da werden die Informationen geladen)

if use advancedsettings.xml and sources.xml it also have to read the library from actual profile.
Now, in this moment, it seems like the sources are everytime the same because the "kodi.0.Directory" and "kodi.0.VideoLibrary" will not be updated when change the profile.......
Maybe possible to add something like "currently logged in user" or something like this and update profiles data to adapter. Thx

**Comment by instalator** [comment]
If set kodi.0.Directory - "/" ?

**Comment by mikiline** [comment]
How to do?
Only can set IP in Adapter Settings

i have folder "profiles".....in this folder i have my profiles (each one have 1 folder) in this are the advancedsettings.xml and sources.xml

but everytime i change the userprofile it have the same sources. it not show me which movie is playing from me different profile.

**Comment by instalator** [comment]
See https://kodi.wiki/view/JSON-RPC_API/v8
If it works, then write

**Comment by mikiline** [comment]
little bit more info please....what should i do? read how the api works? should change something in adapter?

**Comment by instalator** [comment]
https://kodi.wiki/view/JSON-RPC_API/v8#VideoLibrary.GetMovies

**Comment by mikiline** [comment]
the adapter take the wrong source! and i not understand what i should with this link to api.....if you do one more profile you will see what i mean and understand my problem.

**Comment by instalator** [comment]
what gives the API?
http://192.168.1.205:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:1,%22method%22:%22VideoLibrary.GetMovies%22,%22params%22:{%22properties%22:[%22director%22,%22genre%22,%22plot%22,%22rating%22,%22runtime%22,%22sorttitle%22,%22studio%22,%22title%22,%22trailer%22,%22playcount%22,%22originaltitle%22,%22tagline%22,%22imdbnumber%22,%22year%22,%22set%22,%22setid%22,%22dateadded%22,%22top250%22,%22file%22,%22thumbnail%22,%22resume%22,%22streamdetails%22,%22country%22,%22tag%22,%22mpaa%22,%22fanart%22,%22cast%22,%22votes%22,%22writer%22],%22limits%22:{%22start%22:0,%22end%22:500}}}

**Comment by mikiline** [comment]
{"id":1,"jsonrpc":"2.0","result":{"limits":{"end":500,"start":0,"total":98}}}

what is the difference about kodi.0.info and kodi.0 ?
if i watch movie i can see movie title in kodi.0.currentplay.....but i see my last serie in kodi.0.info

**Comment by mikiline** [comment]
i also get this response in adapter log 
Error: SyntaxError: Failed to handle response: Unexpected token � in JSON at position 0

**Comment by instalator** [comment]
kodi.0.info--->  - Player.GetItem
kodi.0 - name info.file or info.label

**Comment by mikiline** [comment]
Hmmmm, OK this i have now. think also something not really right ?

![1](https://user-images.githubusercontent.com/33197125/37786965-367ebd04-2dfe-11e8-8568-71e2e655b195.PNG)
![2](https://user-images.githubusercontent.com/33197125/37786974-3fa66792-2dfe-11e8-8e52-8e894e7fa1d7.PNG)
