### ISSUE TITLE
Artistbild nicht sichtbar

### ISSUE THREAD

**Issue by sigi2345** [instalator/ioBroker.kodi#22]
Hallo,

was muss ich einstellen um das Bild zusehen?

![screenshot 600](https://user-images.githubusercontent.com/41079106/45208954-1dcdeb00-b28c-11e8-9393-2fbaa2c7eacb.png)

**Comment by instalator** [comment]
setting web server

**Comment by sigi2345** [comment]
> setting web server

iobroker or Host?

Are you planning an update?

**Comment by instalator** [comment]
> > setting web server
> > Kodi run on Windows 10
> > iobroker or Host?
> 
> Is this corect?
> 
> ![Screenshot (2268)](https://user-images.githubusercontent.com/41079106/78998317-a8ea2380-7b48-11ea-9f4c-5e94cf159efa.png)
> 
> ![Screenshot (2270)](https://user-images.githubusercontent.com/41079106/78998440-e64eb100-7b48-11ea-94eb-62738207629b.png)
> 
> ![Screenshot (2272)](https://user-images.githubusercontent.com/41079106/78998564-3168c400-7b49-11ea-955e-2012207322a6.png)
> 
> Are you planning an update?
> 
> I have a new Version of js-controller ! V 3.0.5 Beta
> 
> `
> 
> kodi.0	2020-04-10 16:41:21.548	info	(6096) stateChange kodi.0.next {"val":"","ack":false,"ts":1586529681547,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529624950}
> kodi.0	2020-04-10 16:41:08.310	info	(6096) stateChange kodi.0.stop {"val":"","ack":false,"ts":1586529668309,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529668309}
> kodi.0	2020-04-10 16:41:07.206	info	(6096) stateChange kodi.0.next {"val":"","ack":false,"ts":1586529667205,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529624950}
> kodi.0	2020-04-10 16:41:05.146	info	(6096) stateChange kodi.0.playid {"val":2,"ack":false,"ts":1586529665145,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529662688}
> kodi.0	2020-04-10 16:41:04.118	info	(6096) stateChange kodi.0.playid {"val":2,"ack":false,"ts":1586529664116,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529662688}
> kodi.0	2020-04-10 16:41:04.000	info	(6096) stateChange kodi.0.playid {"val":2,"ack":false,"ts":1586529663998,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529662688}
> kodi.0	2020-04-10 16:41:02.689	info	(6096) stateChange kodi.0.playid {"val":2,"ack":false,"ts":1586529662688,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529662688}
> kodi.0	2020-04-10 16:40:48.079	info	(6096) sending in KODI: Player.GoTo - {"playerid":0,"to":1}
> kodi.0	2020-04-10 16:40:48.079	info	(6096) stateChange kodi.0.playid {"val":1,"ack":false,"ts":1586529648078,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529647077}
> kodi.0	2020-04-10 16:40:47.078	info	(6096) sending in KODI: Player.GoTo - {"playerid":0,"to":1}
> kodi.0	2020-04-10 16:40:47.078	info	(6096) stateChange kodi.0.playid {"val":1,"ack":false,"ts":1586529647077,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529647077}
> kodi.0	2020-04-10 16:40:36.076	info	(6096) sending in KODI: Input.ExecuteAction - "skipnext"
> kodi.0	2020-04-10 16:40:36.075	info	(6096) stateChange kodi.0.next {"val":"","ack":false,"ts":1586529636074,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529624950}
> kodi.0	2020-04-10 16:40:24.952	info	(6096) sending in KODI: Input.ExecuteAction - "skipnext"
> kodi.0	2020-04-10 16:40:24.951	info	(6096) stateChange kodi.0.next {"val":"","ack":false,"ts":1586529624950,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1586529624950}
> kodi.0	2020-04-10 16:24:01.514	info	(6096) KODI connected
> kodi.0	2020-04-10 16:24:01.479	error	(6096) Error: Server responded with error: Failed to execute method.
> kodi.0	2020-04-10 16:24:01.399	info	(6096) KODI connected
> kodi.0	2020-04-10 16:23:04.369	info	(6096) starting. Version 1.0.0 in C:/Program Files/iobroker/Test/node_modules/iobroker.kodi, node: v10.16.3, js-controller: 3.0.5
> kodi.0	2020-04-10 16:23:04.139	warn	(6096) This object will not be created in future versions. Please report this to the developer.
> kodi.0	2020-04-10 16:23:04.138	warn	(6096) Object kodi.0.playid is invalid: obj.common.type has an invalid value (integer) but has to be one of number, string, boolean, array, object, mixed, file, json
> `

NO!
PORT webserver in settings.
not 9090, probably 8080

**Comment by sigi2345** [comment]
Thx, run on 8080
Please close it.
