### ISSUE TITLE
Add smart playlist not working

### ISSUE THREAD

**Issue by allofmex** [instalator/ioBroker.kodi#24]
In current release, Kodi's (Smart-)Playlist files cannot be loaded. Only files or folders are working.

I found a **solution** already:
Please change file kodi.js as following:

    `case "add":
                var type;
                ....
                    type = {'playlistid': playlist_id, 'item': {'file': param}};
    CHANGE-->> if (param.slice(-1) === '\\' || param.slice(-1) === '/'){ 
    TO  -->>   if (param.slice(-1) === '\\' || param.slice(-1) === '/' || param.slice(-4) === '.xsp'){
                    type = {'playlistid': playlist_id, 'item': {'directory': param}};
                }
                sendCommand('Playlist.Add', type, function (){
               ....
                break;
`

A short instruction would be nice too:
_To load a (smart) playlist from Visualisation, use Object "kodi.0.add". 
Value must be "special://profile/playlists/music/smart-playlist-filename.xsp"_

Thank you very much.

**Comment by instalator** [comment]
ok
