### ISSUE TITLE
Is this adapter still supported?

### ISSUE THREAD

**Issue by Killi138** [instalator/ioBroker.kodi#36]
There are open issues since 2017 - 3 years ago. Is this adapter still supported or could it be deleted from the iobroker instance-list?

**Comment by instalator** [comment]
You can remove it if you do not need it.

**Comment by thatso** [comment]
@instalator : wow ...what kind of answer was **that** supposed to be?
How about a simple "yes" or no"?
Regarding the fact that issues got no reply for years, I suppose its "no".
How about if I do need this adapter? Shall I still remove it because it is no longer maintained?

**Comment by instalator** [comment]
![IMG_20200403_104814](https://user-images.githubusercontent.com/11523624/78322356-b4fa4200-7598-11ea-9fbf-892b3349527d.jpg) ?

**Comment by thatso** [comment]
@instalator so you closed lots of issues today without actually solving them. What does your screenshot prove? Does "no pull requests" mean "no, this is no longer supported as nobody contributes code updates"?
