### ISSUE TITLE
info/connection (indicator.connected) not updating

### ISSUE THREAD

**Issue by thatso** [instalator/ioBroker.kodi#40]
Once connected, the latest KODI adapter 1.0.0 with KODI 18.2 always shows `info/connection` as `true` and never changes back to `false` despite KODI is no longer running and thus not reachable via network.

**Comment by instalator** [comment]
if the error persists, reopen the question

**Comment by thatso** [comment]
@instalator of course this error persists. It does not magically disappear just because you closed this issue without any actions.
