### ISSUE TITLE
missing datapoint

### ISSUE THREAD

**Issue by dos1973** [instalator/ioBroker.kodi#43]
hi,

I use long time the kodi adapter only to display movie information to my VIS.

after the last update I recognize some datapoint are not updated, and some are complete gone

kodi.0.info.originaltitle
kodi.0.currentplay
kodi.0.info.fanart
kodi.0.info.thumbnail
...
there are some more. 
could you please add these again as datapoints
thanks in advance

**Comment by dos1973** [comment]
kodi.0.info.plot

**Comment by dos1973** [comment]
sorry, noob error, I closed the issue ;-)

**Comment by instalator** [comment]
> sorry, noob error, I closed the issue ;-)

Understood? everything is working?

**Comment by dos1973** [comment]
no the error still exist. 
(I closed the issue with my post, instead to comment...)

**Comment by instalator** [comment]
kodi.0.currentplay moved to info
The rest is all in place

**Comment by instalator** [comment]
![image](https://user-images.githubusercontent.com/11523624/80963024-601c4680-8e38-11ea-8732-f2a08751f001.png)

**Comment by dos1973** [comment]
sorry, I explain bad.
i have the dp, but they are empty?
only playing time gets data

<img width="1295" alt="Bildschirmfoto 2020-05-04 um 16 14 20" src="https://user-images.githubusercontent.com/46686989/80975694-b7afb780-8e22-11ea-9204-67158f664cf8.png">

**Comment by instalator** [comment]
What version is kodi player?

**Comment by dos1973** [comment]
what I just recognize. 
when a movie is playing and I then restart the Kodi Adapter than I got all the information.
but choose another movie there are again no information.
my Kodi runs on an w10


<img width="1243" alt="Bildschirmfoto 2020-05-04 um 16 27 30" src="https://user-images.githubusercontent.com/46686989/80976810-31947080-8e24-11ea-82d9-c3c9ab31f811.png">

**Comment by dos1973** [comment]
Kodi 18.5

**Comment by dos1973** [comment]
just update to Kodi 18.6
same behavior. 
DP will only have data while playing movie and restarting the Kodi adapter.

**Comment by instalator** [comment]
Have you tried uninstalling and reinstalling the adapter?

**Comment by dos1973** [comment]
yes, same issue.

**Comment by instalator** [comment]
What returns this query?
`http://192.168.88.12:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22id%22:3,%22method%22:%22Player.GetItem%22,%22params%22:{%22playerid%22:1,%22properties%22:[%22album%22,%22albumartist%22,%22artist%22,%22director%22,%22episode%22,%22fanart%22,%22file%22,%22genre%22,%22plot%22,%22rating%22,%22season%22,%22showtitle%22,%22studio%22,%22imdbnumber%22,%22tagline%22,%22thumbnail%22,%22title%22,%22track%22,%22writer%22,%22year%22,%22streamdetails%22,%22originaltitle%22,%22cast%22,%22playcount%22]}}`

**Comment by dos1973** [comment]
{"id":3,"jsonrpc":"2.0","result":{"item":{"album":"","artist":[],"cast":[{"name":"Chris Hemsworth","order":0,"role":"Agent H","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f6fGCcu1bbc0tVCMhQRmeRryGVMa.jpg/"},{"name":"Tessa Thompson","order":1,"role":"Agent M","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2ffycqdiiM6dsNSbnONBVVQ57ILV1.jpg/"},{"name":"Kumail Nanjiani","order":2,"role":"Pawny (voice)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f9EyrK1Cv7ey1h1GgmsVAOn45w6G.jpg/"},{"name":"Rebecca Ferguson","order":3,"role":"Riza","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f4vbZcV22YmWhZqFsAbOkVauIoY7.jpg/"},{"name":"Rafe Spall","order":4,"role":"Agent C","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f5tGhC9MGT4FGaJHr2LGYcRV4rbJ.jpg/"},{"name":"Emma Thompson","order":5,"role":"Agent O","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f2AZaQpfYkvgwYrfqdl9TBoXdjHP.jpg/"},{"name":"Liam Neeson","order":6,"role":"Agent High T","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fiNyV85ll3lqkHA6FMiNzMFNY6Zs.jpg/"},{"name":"Laurent Bourgeois","order":7,"role":"Alien Twin #1","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2ftRnQEILfYe3kGtBJKaqUQk4DoI5.jpg/"},{"name":"Larry Bourgeois","order":8,"role":"Alien Twin #2","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fiqpoQtuMJWyIsAwxyrp5vHdv0Se.jpg/"},{"name":"Kayvan Novak","order":9,"role":"Vungus / Nasr / Bassam","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fy5HFz3JRGTjXTNaaB8eYolZVVeF.jpg/"},{"name":"Spencer Wilding","order":10,"role":"Luca Brasi","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fuF8steIdtweWGf4IvoXWhrafIk6.jpg/"},{"name":"Marcy Harriell","order":11,"role":"Molly's Mom","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fbsmOzgcEciqI1qweGviDSuKj5Ib.jpg/"},{"name":"Inny Clemons","order":12,"role":"Molly's Dad","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fcTWucmhv5kuTbafUpa99azPldki.jpg/"},{"name":"Aaron Serotsky","order":13,"role":"Man in Black #1","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2flDsjTlg2zZa2lVsIo4OBvcxp1oV.jpg/"},{"name":"Mandeiya Flory","order":14,"role":"Young Molly","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2forurETqcnU8txK4AsYheCxPvL8s.jpg/"},{"name":"Matthew Bates","order":15,"role":"FBI HR Guy","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f3lBqXSSJMxjjI5SvqBjM6msywg0.jpg/"},{"name":"Sartaj Garewal","order":16,"role":"CIA Recruiter"},{"name":"Stephen Wight","order":17,"role":"Guy"},{"name":"Brian Silliman","order":18,"role":"Cabbie","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f654Fwfas42Ze5uZxol7GUmf1XAs.jpg/"},{"name":"John Sousa","order":19,"role":"Jimmy the Alien"},{"name":"Jeff Kim","order":20,"role":"Lead MIB Agent","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fxDK3KqQWXBuyXEvldqTQmpp5Mbi.jpg/"},{"name":"Michael Adams","order":21,"role":"MIB Lead Interrogator","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f9KyvmfWqFcotizZqM8TFzXwqtL8.jpg/"},{"name":"Mike Capozzola","order":22,"role":"Veteran MIB Agent","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f3AluVYcyUpO7GpUt4Xc5ea7REvN.jpg/"},{"name":"Annie Burkin","order":23,"role":"Nerlene"},{"name":"Andrew Greenough","order":24,"role":"Freddie the Alien","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f7pfpJjV1UFybbkjlBp5ENByrI9v.jpg/"},{"name":"Natasha Culzac","order":25,"role":"Nightclub Waitress","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fkiehH0tqjSUQxTY2H57zlmqjnuB.jpg/"},{"name":"David Hartley","order":26,"role":"MIB Forensics Agent"},{"name":"Paul Brennen","order":27,"role":"Alien Boss"},{"name":"Ania Sowinski","order":28,"role":"Alien Woman / Boss' Wife"},{"name":"Stefan Kalipha","order":29,"role":"Antique Shopkeeper"},{"name":"Daniel Scott-Smith","order":30,"role":"Nightclub Bartender"},{"name":"Vincent Pirillo","order":31,"role":"MIB Security Guard","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fr8LtEHIbg2iO0QGezY5jBy44T9m.jpg/"},{"name":"Kaya Brown-Hallam","order":32,"role":"NIghtclub Patron #1"},{"name":"Beau Fowler","order":33,"role":"Nightclub Patron #2","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fhm0p4amoCaB3ulCoIwFwCuuYSrg.jpg/"},{"name":"Lukas DiSparrow","order":34,"role":"Nightclub Patron #3","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fprULDEFZylIWC9o2qtjdA0dhhvU.jpg/"},{"name":"Andy Beckwith","order":35,"role":"Viper Room Player"},{"name":"Romanos Blanco","order":36,"role":"Man at Eiffel Tower","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fxIEzlLZgefRFgVTBaR71y7RK6wu.jpg/"},{"name":"AistÄ— DirÅ¾iÅ«tÄ—","order":37,"role":"Woman at Eiffel Tower","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2flKpX2Ulixg1axwedqR9yfspCWON.jpg/"},{"name":"Anatole Taubman","order":38,"role":"French Salesman","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fA7B7POXpFyNg7C36fGxVc4EiR2W.jpg/"},{"name":"Sorel Johnson","order":39,"role":"Nervous Forensic Tech","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fj71OY6vNw4mFEpildageO6vGmCe.jpg/"},{"name":"Paul Smith","order":40,"role":"Proprietor (Charlie)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fwPqcJi55Lj2oLEQMzJHBuUoEvkj.jpg/"},{"name":"Tim Blaney","order":41,"role":"Voice of Frank the Pug (voice)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f8KkdDVZhzXyTEGt0rBOkVviIQ9R.jpg/"},{"name":"Thom Fountain","order":42,"role":"Worm Guy #1 (voice)"},{"name":"Drew Massey","order":43,"role":"Worm Guy #2 (voice)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2frzIYVxTH41JeARIWbcavxVu4mMq.jpg/"},{"name":"Wong Charlie","order":44,"role":"Immigration Alien (uncredited)"},{"name":"Elon Musk","order":45,"role":"Alien on TV Monitor (uncredited)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f52SNpDJJCgBVfZtibLuXN1ZrliC.jpg/"},{"name":"Bern CollaÃ§o","order":46,"role":"MIB Scientist","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fziLGGjo5GWzYDL8H4MUquoFj8r0.jpg/"},{"name":"Elle Black","order":47,"role":"Alien Dancer (uncredited)","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2fo1qYPuIblHClmRzljPWRVJ9G0aB.jpg/"}],"director":["F. Gary Gray"],"episode":-1,"fanart":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f2qdS2DZSQnBeeafG3oXIIy4m2RL.jpg/","file":"smb://192.168.10.216/harddisk/Men In Black_ International.ts","genre":["KomÃ¶die","Science Fiction"],"id":141,"imdbnumber":"tt2283336","label":"Men in Black: International","originaltitle":"Men in Black: International","playcount":0,"plot":"Als junges MÃ¤dchen beobachtete Molly einen Einsatz der Men In Black. Seitdem ist sie fest entschlossen, die Wahrheit Ã¼ber Aliens und die mysteriÃ¶sen MÃ¤nner in den schwarzen AnzÃ¼gen herauszufinden. Sie sucht nach Antworten und entdeckt schlieÃŸlich das Hauptquartier der MIB in New York. Dort ist Agent O  von Mollys Intelligenz und FÃ¤higkeiten beeindruckt und macht aus Molly Agent M. Ihr erster Auftrag fÃ¼hrt sie nach London, wo sie gemeinsam mit Agent H  Vungus, einen AngehÃ¶rigen des auÃŸerirdischen KÃ¶nigshauses treffen. Kurz nach seiner Ankunft wird er in einem noblen Nachtclub ermordet, gibt aber vor seinem Tod noch eine mÃ¤chtige Waffe an M weiter. Die beiden Geheimagenten vermuten einen Maulwurf innerhalb der MIB-Organisation, der die Information Ã¼ber Vungus' Aufenthaltsort weitergegeben haben muss. Sie setzen nun alles daran, den MÃ¶rder und VerrÃ¤ter zu finden, bevor die mÃ¤chtige Waffe in die falschen HÃ¤nde gelangt ...","rating":6.0,"season":-1,"showtitle":"","streamdetails":{"audio":[{"channels":2,"codec":"ac3","language":"deu"},{"channels":2,"codec":"ac3","language":"eng"}],"subtitle":[],"video":[{"aspect":1.7777780294418336,"codec":"h264","duration":7140,"height":1080,"language":"","stereomode":"","width":1920}]},"studio":["Amblin Entertainment"],"tagline":"Das Universum wird grÃ¶ÃŸer","thumbnail":"image://http%3a%2f%2fimage.tmdb.org%2ft%2fp%2foriginal%2f3J8ftplDfN7CVK2XkuFs4JEkRJN.jpg/","title":"Men in Black: International","track":-1,"type":"movie","writer":["Art Marcum","Matt Holloway"],"year":2019}}}

**Comment by instalator** [comment]
update with github

**Comment by dos1973** [comment]
sorry, don't understand?

**Comment by dos1973** [comment]
like this?
<img width="518" alt="Bildschirmfoto 2020-05-04 um 17 57 04" src="https://user-images.githubusercontent.com/46686989/80986325-b5ecf080-8e30-11ea-8cb9-493550b1b8b3.png">

**Comment by instalator** [comment]
yes

**Comment by dos1973** [comment]
looks very very good ;-) DP have Data.
I'll will doublecheck later again.

Thanks for you help!

**Comment by dos1973** [comment]
the only thing is miss is the dp
kodi.0.info.tagline

its only update by some movies, but currently will not be filled.

**Comment by dos1973** [comment]
Thanks a lot, this one is solved.
