### ISSUE TITLE
Decode Fanart and Thumbnail

### ISSUE THREAD

**Issue by dos1973** [instalator/ioBroker.kodi#44]
Hi,

cloud you please decode this 2 DP
kodi.0.info.thumbnail
kodi.0.info.fanart

should be an ready for browser, so I can use directly in vis as source
like this one: 

http://image.tmdb.org/t/p/original/tpaM9bgn5rJq2Tet7LEqju0MUbC.jpg

currently I have an additional script, 
but would be perfect to this directly into the Kodi Adapter.

`function decode(url) {
    // image:// am Anfang und / am Ende abschneiden
    url = url.slice(8).slice(0, -1);
    url = decodeURIComponent(url);
    return url;
}
 
on("kodi.0.info.fanart", obj => {
    if (obj.state && obj.state.val) {
        const url = decode(obj.state.val);
        setState("0_userdata.0.Wohnung.Kino.Kodi_Cover.Fanart", url, true);
    }
});
 
on("kodi.0.info.thumbnail", obj => {
    if (obj.state && obj.state.val) {
        const url = decode(obj.state.val);
        setState("0_userdata.0.Wohnung.Kino.Kodi_Cover.Thumbnail", url, true);
    }
});`

thanks and greetings from Germany

**Comment by instalator** [comment]
You can just use kodi widgets.
since your case does not take into account that fanart may be local

**Comment by instalator** [comment]
For example:
image://music@nfs%3a%2f%2f192.168.88.11%2fvolume1%2fMusic%2fFlac%2fAtlantidaProject%2fAtlantida%20project%20-%20New%20dimension%202010%2f01%20Atlantida%20project%20-%20%d0%93%d0%b0%d1%80%d0%bc%d0%be%d0%bd%d0%b8%d1%87%d0%b5%d1%81%d0%ba%d0%b0%d1%8f%20%d0%b3%d0%b0%d0%bc%d0%bc%d0%b0.flac/

**Comment by instalator** [comment]
![image](https://user-images.githubusercontent.com/11523624/81059681-1ba5af00-8efb-11ea-8726-c93260c82ffd.png)

**Comment by dos1973** [comment]
Hi,

Thanks for the hint, 
but the images will not been shown on any of my mobile devices. Iphone, ipad aswell into the fully browser. 

On desktop every works fine
