### ISSUE TITLE
Kodi Thumbnails

### ISSUE THREAD

**Issue by dos1973** [instalator/ioBroker.kodi#46]
Hi,

sorry to open again a new issue, but don't find a option to reopen the topic before.
you mentioned how to display the covers and this is great an better the my version to point online.
https://github.com/instalator/ioBroker.kodi/issues/44

but I have still an issue urn mobile devices. The image will not be visible.
do i have anything wrong. could you reproduce this?

**Comment by instalator** [comment]
I don’t understand what kind of problem is on the mobile device, is the device located on the local network?

**Comment by dos1973** [comment]
yes, the device are into the same local wlan.

same vis, all same.
the desktop devices presents the icon. the mobile devices don't show it.
strange!

**Comment by instalator** [comment]
Which browser is used on mobile?

**Comment by dos1973** [comment]
on my apple devices iPhone/iPad I tried safari and chrome.
my android use fully.

all have the same behavior, no images.

all desktops, windows & mac (safari and chrome), works perfect

**Comment by instalator** [comment]
Kodi WEB interface opens from mobile devices?

**Comment by dos1973** [comment]
yes it opens from the mobile.

**Comment by instalator** [comment]
Send a screenshot of how it looks

**Comment by dos1973** [comment]
here you see, my MacBook with the open vis page where the display is open.
the iPad in front of have the same vis page open. the iPad is int the same plan
![IMG_0847-1](https://user-images.githubusercontent.com/46686989/81299403-79123b00-9076-11ea-8dc6-c01f5ceccb0f.JPG)

here you see the Kodi web on the same iPad, btw. same movie
![IMG_0092](https://user-images.githubusercontent.com/46686989/81299532-a52dbc00-9076-11ea-885e-4eae7ace357d.PNG)

**Comment by instalator** [comment]
![photo_2020-05-07_20-48-55](https://user-images.githubusercontent.com/11523624/81302235-4a12be00-90a4-11ea-82fa-78d1995d7424.jpg)

**Comment by dos1973** [comment]
looks good ;-)
any ideas what I can check more?

**Comment by instalator** [comment]
Update adapter with github

**Comment by dos1973** [comment]
Me too.
What would be the path/ link to the image
Id like to try directly in the browser

**Comment by instalator** [comment]
Have you updated the github adapter?

**Comment by dos1973** [comment]
Just doing, saw you last post too late. One minute

**Comment by dos1973** [comment]
No :(
Still v2.02?

**Comment by instalator** [comment]
![image](https://user-images.githubusercontent.com/11523624/81305733-e212a680-90a8-11ea-8d3b-059b8b616dd4.png)

**Comment by dos1973** [comment]
Yes, i did it

**Comment by instalator** [comment]
I did not change the version in the repository

**Comment by dos1973** [comment]
No, than it don’t change anything
Still no images

**Comment by instalator** [comment]
I don’t know the reason, I don’t have an apple device for testing.

**Comment by dos1973** [comment]
Not only ios.
Happen same on an android device and fully browser

**Comment by instalator** [comment]
On all android devices on which I checked it works

**Comment by instalator** [comment]
Do you open the VIS page on your mobile device?

**Comment by dos1973** [comment]
Not sure if understood correct.

yes, i use the vis on my mobile devices, but only in my local wlan


________________________________
Von: Vladimir Vilisov <notifications@github.com>
Gesendet: Friday, May 8, 2020 11:44:34 AM
An: instalator/ioBroker.kodi <ioBroker.kodi@noreply.github.com>
Cc: dos1973 <dos1973@live.de>; Author <author@noreply.github.com>
Betreff: Re: [instalator/ioBroker.kodi] Kodi Thumbnails (#46)


Do you open the VIS page on your mobile device?

**Comment by instalator** [comment]
Show a screenshot of widget settings. Tried to clear the browser cache on the device?

**Comment by dos1973** [comment]
this is how its configured

<img width="459" alt="Bildschirmfoto 2020-05-08 um 11 56 53" src="https://user-images.githubusercontent.com/46686989/81394972-1dea5200-9123-11ea-860d-d183cefeaf79.png">

**Comment by dos1973** [comment]
I have delete the cache... everything.
no change.

**Comment by dos1973** [comment]
I got it!!!!
the error is the Kodi user/ password. The VIS don't ask for it.
after I delete this in the Kodi Config, the image is visible...

![image0](https://user-images.githubusercontent.com/46686989/81397434-99e69900-9127-11ea-93b5-29c5dbc5889b.jpeg)

**Comment by instalator** [comment]
Congratulations. I close the question.

**Comment by dos1973** [comment]
may I ask you something more from the 1st post, regarding the tagline value

**Comment by instalator** [comment]
Yes of course

**Comment by dos1973** [comment]
no value in DP 
kodi.0.info.tagline

**Comment by instalator** [comment]
Update adapter with github

**Comment by dos1973** [comment]
perfect. 
Thanks a lot for all your help & effort.

I'd like to setup an password, in Kodi - so if you could manage these, would be great... but for now I'm happy. If I can help you onetime, by testing anything, please let me know.

**Comment by instalator** [comment]
API does not use passwords. Password in settings and only for web page

**Comment by dos1973** [comment]
whatever ?!
;-)

can be closed.
