### ISSUE TITLE
Please better qualify the css classes

### ISSUE THREAD

**Issue by oweitman** [instalator/ioBroker.kodi#47]
In your styles.css you have some generic named css-classes (eg stop prev next)
If someone else uses the CSS classes stop, the generically formulated CSS styles also interfere with other elements.

Please add more specification to your css classes:

e.g. for stop
.kodi.stop {background: url ("../ img / btn / btn_sprite.png") -528px 48px;}

https://github.com/instalator/ioBroker.kodi/blob/2b7380004f8d8a5a86e50a3d3a56f7a509776854/widgets/kodi/css/style.css#L93

see also
https://forum.iobroker.net/topic/33376/test-adapter-mytime-v0-1-x/9

**Comment by oweitman** [comment]
If somebody else use the css class eg „stop“ your not full qualified css selectors Leads to css artefacts 
![](https://forum.iobroker.net/assets/uploads/files/1591866228501-anmerkung-2020-06-11-110143.png)

**Comment by instalator** [comment]
Test on 2.0.5

**Comment by oweitman** [comment]
i cannot retest, because a user of my widgets reported this, but it looks ok
in meantime i changed my css to a different name
thank you
