### ISSUE TITLE
Update stable version in repo from 2.0.1 to 2.0.4

### ISSUE THREAD

**Issue by GermanBluefox** [instalator/ioBroker.kodi#48]
# Think about update stable version to 2.0.4
**Version**: stable=**2.0.1** (55 days old) => latest=**2.0.4** (30 days old)
**Installs**: stable=**550** (37.67%), latest=**302** (20.68%), total=**1460**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L643)

**Comment by instalator** [comment]
fixed
