### ISSUE TITLE
Fehler nach dem Connect

### ISSUE THREAD

**Issue by AlGu318** [instalator/ioBroker.kodi#5]
Hallo,

bei mir zeigt der Adapter einen Fehler nach dem "connect":
"kodi.0 Error: Server response with error: Failed to execute method."

Um den Fehler etwas einzugrenzen habe ich bei mir Log-Einträge hinzugefügt und die Stelle gefunden an der er hinfällt: (im kodi.js in der Mehtode "GetChannels": Zeile 595 wird aufgerufen und landet dann in Zeile 599.)
Ich denke es liegt daran, dass die "alltv" und "allradio" (bei mir) leer sind, wenn ich mir mit "JSON.stringify(alltv)" den Inhalt anzeigen lasse, dann steht da nur "{}" im log.

Vielleicht hilft das bei der Fehleranalyse oder dem Nachstellen.

Gruß AlGu

**Comment by instalator** [comment]
https://github.com/instalator/iobroker.kodi/commit/f53a37819bb9463afc98c6ba209e967b308ff0f7
Check now

**Comment by instalator** [comment]
Working?

**Comment by AlGu318** [comment]
[kodi.zip](https://github.com/instalator/iobroker.kodi/files/1269535/kodi.zip)

Ich habe mal meine Anpassungen hier hinzugefügt, damit kommt der Fehler nicht mehr.
Gruß AlGu

**Comment by instalator** [comment]
Okay, können Sie eine Pull requests machen?

**Comment by cernst1980** [comment]
+1

error: kodi.0 Error: Server responded with error: Failed to execute method.

**Comment by mikiline** [comment]
+ 1 error: kodi.0 Error: Server responded with error: Failed to execute method
![kodiconnect](https://user-images.githubusercontent.com/33197125/48060061-2888fb80-e1bb-11e8-94f8-a318e8108c6b.PNG)
