### ISSUE TITLE
Connection to Kodi failed

### ISSUE THREAD

**Issue by distler959** [instalator/ioBroker.kodi#52]
Hello,

The Kodi adapter flashes green / yellow at short intervals. It connects and breaks the connection in very short time intervals. The result is that no connection is possible and the objects are not updated.
I tried the usual options, of course:
Reboot and reinstall the adapter etc.
Played another movie, played music, etc.

Kodi can be accessed via a browser and is therefore connected.
Here is my compilation:

IOBroker on Synology DS918 + with Docker
Adapter Kodi version 2.0.4
Kodi 17.5 on an HTPC with Win

LOG:
https://forum.iobroker.net/assets/uploads/files/1603897391635-0f49755e-ffe5-4a08-a0dc-26aced946fbc-grafik.png

Thanks in advance

Best regards
Dominik

**Comment by instalator** [comment]
adapter is not supported for older kodi versions
