### ISSUE TITLE
feature request: (music) userrating and album userrating

### ISSUE THREAD

**Issue by realwax** [instalator/ioBroker.kodi#57]
Great adapter! Eases a lot :) Thank you!

May I kindly ask to implement the userrating value for music played and for the belonging album rating (iuserrating in the db). Would be great to have it read out and the ability to set it. That would allow us to work with smart playlists of rated songs / albums and created Alexa or remote button workflows to user rate your own music. 
I'll do it with curl for now as my coding skills aren't to great. Otherwise I would contribute a suggestion... 

Thnak you!
Cheers
WaX

Song Detail:
{"jsonrpc": "2.0", "method": "AudioLibrary.GetSongDetails", "params": { "songid": 68579 , "properties": ["albumid" , "userrating"] }, "id": "libSongs"}

Album Detail:
{"jsonrpc": "2.0", "method": "AudioLibrary.GetAlbumDetails", "params": { "albumid": 1328 , "properties": ["userrating"] }, "id": "libSongs"}

Set Song Userrating
{"jsonrpc": "2.0", "method": "AudioLibrary.SetSongDetails", "params": { "songid": 68579 , "userrating": 10 }, "id": "libSongs"}

Set Album Userrating
{"jsonrpc": "2.0", "method": "AudioLibrary.SetAlbumDetails", "params": { "albumid": 1328 , "userrating": 10 }, "id": "libSongs"}

Current Song played rating and albumid
{"jsonrpc": "2.0", "method": "Player.GetItem", "params": { "properties": ["userrating" , "albumid"], "playerid": 0 }, "id": "AudioGetItem"}

**Comment by instalator** [comment]
Do you need to get data only during playback?

**Comment by realwax** [comment]
Thanks for the quick reply!
Yes, only of the song playing currently. 

The userrating of the song can be queried by method": "Player.GetItem". That sends the current song details. The property  userrating must be set. If you query the belonging albumid id as well you can then use it to query AudioLibrary.GetAlbumDetails.

Please see the jsonrpc calls above.

Maybe to query the albumrating of a belonging song playing is too special for general purpose and exceeds scope of the adapter but it would be great to at least query and set the userrating of the song playing.

The benefit as said above is a very smart way to whether press a button or tell you voice assistant you like the song or the album. On another day you call your random most liked songs. 

Building your own spotify ;) 


So this is part of my blockly script using curl and the api to query and post the ratings. Maybe this is interesting for more users. Maybe not. I guess it would be a good option in iobroker allowing to set  both. ;) 

`
async function modifyuserratings(what, desiredrating) {
  exec('curl -u kodi:kodi -d \'{"jsonrpc": "2.0", "method": "Player.GetItem", "params": { "properties": ["userrating" , "albumid"], "playerid": 0 }, "id": "AudioGetItem"}\' -H "Content-Type: application/json" -X POST http://10.0.0.40:8080/jsonrpc', async function (error, result, stderr) {
      songid = getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result.item.id');
    albumid = getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result.item.albumid');
    userrating = getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result.item.userrating');
    exec((['curl -u kodi:kodi -d \'{"jsonrpc": "2.0", "method": "AudioLibrary.GetAlbumDetails", "params": { "albumid": ',albumid,' , "properties": ["userrating"] }, "id": "libSongs"}\' -H "Content-Type: application/json" -X POST http://10.0.0.40:8080/jsonrpc'].join('')), async function (error, result, stderr) {
        albumuserrating = getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result.albumdetails.userrating');
    });
    console.log("exec: " + (['curl -u kodi:kodi -d \'{"jsonrpc": "2.0", "method": "AudioLibrary.GetAlbumDetails", "params": { "albumid": ',albumid,' , "properties": ["userrating"] }, "id": "libSongs"}\' -H "Content-Type: application/json" -X POST http://10.0.0.40:8080/jsonrpc'].join('')));
    if (what == 'song') {
      exec((['curl -u kodi:kodi -d \'{"jsonrpc": "2.0", "method": "AudioLibrary.SetSongDetails", "params": { "songid": ',songid,' , "userrating": ',desiredrating,' }, "id": "libSongs"}\' -H "Content-Type: application/json" -X POST http://10.0.0.40:8080/jsonrpc'].join('')), async function (error, result, stderr) {
          setState("alexa2.0.Echo-Devices.G090XG07939309UQ.Commands.speak"/*speak*/, (getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result') == 'OK' ? 'Song rating set!' : 'Error setting song rating'));
      });
    } else if (what == 'album') {
      exec((['curl -u kodi:kodi -d \'{"jsonrpc": "2.0", "method": "AudioLibrary.SetAlbumDetails", "params": { "albumid": ',albumid,' , "userrating": ',desiredrating,' }, "id": "libSongs"}\' -H "Content-Type: application/json" -X POST http://10.0.0.40:8080/jsonrpc'].join('')), async function (error, result, stderr) {
          setState("alexa2.0.Echo-Devices.G090XG07939309UQ.Commands.speak"/*speak*/, (getAttr((function () { try {return JSON.parse(result);} catch(e) {return {};}})(), 'result') == 'OK' ? 'Album  rating set!' : 'Error setting album rating!'));
      });
    }
  });
}

`

**Comment by instalator** [comment]
Update from github and check

**Comment by realwax** [comment]
Wow! That was a very quick one! Tested - works! 

Thanks a lot :) 



kodi.0 | 2021-03-04 12:13:29.380 | info | (28909) sending in KODI: AudioLibrary.SetAlbumDetails - {"albumid":4240,"userrating":10}
-- | -- | -- | --
kodi.0 | 2021-03-04 12:13:25.519 | info | (28909) sending in KODI: AudioLibrary.SetSongDetails - {"songid":110651,"userrating":10}
kodi.0 | 2021-03-04 12:13:20.154 | info | (28909) sending in KODI: AudioLibrary.SetSongDetails - {"songid":110651,"userrating":10}

http://10.0.0.40:8080/jsonrpc?request={%22jsonrpc%22:%20%222.0%22,%20%22method%22:%20%22AudioLibrary.GetAlbumDetails%22,%20%22params%22:%20{%20%22albumid%22:%204240%20,%20%22properties%22:%20[%22userrating%22]%20},%20%22id%22:%20%22libSongs%22}

{"id":"libSongs","jsonrpc":"2.0","result":{"albumdetails":{"albumid":4240,"label":"Chillhop Essentials: Winter 2016","userrating":10}}}

**Comment by instalator** [comment]
i change object userrating_song to userrating. universal for audio and local video

**Comment by realwax** [comment]
Yes makes sense. Thanks - updated and changed!
