### ISSUE TITLE
Crashing with clear

### ISSUE THREAD

**Issue by realwax** [instalator/ioBroker.kodi#58]
Hi,

Even though you have implemented the fix the adapter crashes on "clear playlist" again.

kodi.0 | 2021-03-04 16:30:54.798 | warn | (23754) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
kodi.0 | 2021-03-04 16:30:54.797 | info | (23754) terminating
kodi.0 | 2021-03-04 16:30:54.796 | debug | (23754) cleaned everything up...
kodi.0 | 2021-03-04 16:30:54.780 | error | (23754) Cannot read property 'undefined' of undefined
kodi.0 | 2021-03-04 16:30:54.779 | error | (23754) TypeError: Cannot read property 'undefined' of undefined at saveState (/opt/iobroker/node_modules/iobroker.kodi/kodi.js:520:22) at ConstructorCmd (/opt/iobroker/node_modules/iobroker.k
kodi.0 | 2021-03-04 16:30:54.776 | error | (23754) uncaught exception: Cannot read property 'undefined' of undefined
kodi.0 | 2021-03-04 16:30:54.774 | debug | (23754) ConstructorCmd null - clear = true
kodi.0 | 2021-03-04 16:30:54.771 | debug | (23754) state kodi.0.clear changed: true (ack = false)

Thank you

**Comment by instalator** [comment]
fixed 2.0.6

**Comment by realwax** [comment]
Thank you!
