### ISSUE TITLE
playlist wird nicht eingelesen

### ISSUE THREAD

**Issue by arteck** [instalator/iobroker.kodi#7]
mjit der neuen Jarvis Version von Kodi bleibt die Playlist leer
![grafik](https://cloud.githubusercontent.com/assets/6681528/23330041/fe200784-fb44-11e6-84c2-1fa67324c182.png)

**Comment by instalator** [comment]
Use http://www.iobroker.net/?page_id=6489&lang=ru

**Comment by arteck** [comment]
no its not same problem

**Comment by instalator** [comment]
Use only this widgets
http://www.iobroker.net/docu/?page_id=6489&lang=ru
